"use client"

import type { DealOutput } from "@/types";
import { KpiCard } from "./KpiCard";
import { DollarSign, Banknote, Percent, Building } from 'lucide-react';

interface KpiDashboardProps {
    output: DealOutput;
}

export function KpiDashboard({ output }: KpiDashboardProps) {
    const kpis = [
        { title: 'Net Operating Income (NOI)', value: output.noi, format: 'currency', icon: <DollarSign />, tooltip: 'Annual income generated by the property after operating expenses.' },
        { title: 'Cash Flow (Annual)', value: output.cashFlow, format: 'currency', icon: <Banknote />, tooltip: 'Money left over after all expenses, including mortgage payments.' },
        { title: 'Cap Rate', value: output.capRate, format: 'percent', icon: <Building />, tooltip: 'The rate of return on the property based on its income.' },
        { title: 'Cash on Cash Return', value: output.cashOnCashReturn, format: 'percent', icon: <Percent />, tooltip: 'The rate of return on the actual cash invested.' },
    ];

    return (
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4 no-print">
            {kpis.map(kpi => (
                <KpiCard key={kpi.title} {...kpi} />
            ))}
        </div>
    );
}
